# tasks file for aws-ec2_role

- name: "Creating Key Pair In AWS"
  amazon.aws.ec2_key:
    name: "ansible_key_2"
    key_material: "{{ lookup('file', '/root/.ssh/ansible_key_2.pub') }}"
    region: "ap-south-1"
    state: present
    aws_secret_key: "{{secret_key}}"
    aws_access_key: "{{access_key}}"


- name: "Create Security Group"
  amazon.aws.ec2_security_group:
    name: "sg_ansible_project"
    description: "Security group"
    region: "ap-south-1"
    aws_access_key: "{{access_key}}"
    aws_secret_key: "{{secret_key}}"
    rules:
      - proto: all
        from_port: 0
        to_port: 0
        cidr_ip: 0.0.0.0/0
        rule_desc: "allow everyone on http and ssh port"

- name: "Launching AWS ec2 Instance"
  amazon.aws.ec2_instance:
    aws_access_key: "{{access_key}}"
    aws_secret_key: "{{secret_key}}"
    name: "Backend Server"
    region: "ap-south-1"
    key_name: "ansible_key_2"
    image_id: "ami-0d3f444bc76de0a79"
    instance_type: "t2.micro"
    tags:
        environment: "testing"
    security_group: "sg_ansible_project"
    network:
      assign_public_ip: true
    count: 1
    wait_timeout: 300
  register: info
  ignore_errors: true

- name: "Adding Hosts to Inventory"
  add_host:
    name: "{{info.instances[0].public_ip_address}}"
    ansible_user: "ec2-user"
    ansible_ssh_private_key_file: "ansible_key_2.pem"
    ansible_connection: "ssh"
    groups: "web"

- name: "Updating Host file"
  lineinfile:
    path: /etc/ansible/hosts
    line: "{{info.instances[0].public_ip_address}} ansible_user=ec2-user  ansible_ssh_private_key_file=ansible_key_2.pem ansible_connection=ssh"
    insertbefore: "[LB]"
  delegate_to: localhost


- lineinfile:
    path: /etc/ansible/hosts
    line: " "
    insertbefore: "[LB]"

- wait_for:
    timeout: 20

- name: "debugging the groups info"
  debug:
    var: groups['web']

                                                       
